export const IMPORT_TELEMETRY_CODES = {
  INPUT_ACCEPTED: "IMPORT_INPUT_ACCEPTED",
  PARSE_START: "IMPORT_PARSE_START",
  PARSE_OK: "IMPORT_PARSE_OK",
  PARSE_FAILED: "IMPORT_PARSE_FAILED",
  EXTERNALREFS_MAP_START: "IMPORT_EXTERNALREFS_MAP_START",
  EXTERNALREFS_MAP_STATS: "IMPORT_EXTERNALREFS_MAP_STATS",
  PROVENANCE_NODE_MISS: "IMPORT_PROVENANCE_NODE_MISS",
  PROVENANCE_EDGE_MISS: "IMPORT_PROVENANCE_EDGE_MISS",
  VALIDATE_PARSE_START: "IMPORT_VALIDATE_PARSE_START",
  VALIDATE_PARSE_OK: "IMPORT_VALIDATE_PARSE_OK",
  VALIDATE_INVARIANTS_START: "IMPORT_VALIDATE_INVARIANTS_START",
  VALIDATE_INVARIANTS_OK: "IMPORT_VALIDATE_INVARIANTS_OK",
  NORMALIZE_START: "IMPORT_NORMALIZE_START",
  NORMALIZE_OK: "IMPORT_NORMALIZE_OK",
  REPARSE_START: "IMPORT_REPARSE_START",
  REPARSE_OK: "IMPORT_REPARSE_OK",
  REVALIDATE_START: "IMPORT_REVALIDATE_START",
  REVALIDATE_OK: "IMPORT_REVALIDATE_OK",
  FINALIZE_SUMMARY: "IMPORT_FINALIZE_SUMMARY",
  PIPELINE_FAILED: "IMPORT_PIPELINE_FAILED",
} as const;

export type ImportTelemetryCode =
  (typeof IMPORT_TELEMETRY_CODES)[keyof typeof IMPORT_TELEMETRY_CODES];

export const IMPORT_TELEMETRY_WARNING_CODES = [
  IMPORT_TELEMETRY_CODES.PROVENANCE_NODE_MISS,
  IMPORT_TELEMETRY_CODES.PROVENANCE_EDGE_MISS,
] as const;

export const IMPORT_TELEMETRY_FAILURE_CODES = [
  IMPORT_TELEMETRY_CODES.PARSE_FAILED,
  IMPORT_TELEMETRY_CODES.PIPELINE_FAILED,
] as const;
